[package]
name = "colori-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
colori-core = { path = "../colori-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = { version = "0.8", features = ["small_rng"] }
